version: "3.3"
services:
  data-load-series:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=redis_data_load_series
    image: data-load-series:latest
    container_name: data-load-series
    environment:
      - FILENAME=seriesSiantel081019.txt
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_PASS=TeLcEl
      - OMP_NUM_THREADS=3
    volumes: 
      - type: bind
        source: ./data
        target: /data
    networks:
      - redis-net
    depends_on:
      - redis
  data-load-planes:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=redis_data_load_planes
    image: data-load-planes:latest
    container_name: data-load-planes
    environment:
      - FILENAME=Planes.txt
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_PASS=TeLcEl
    volumes: 
      - type: bind
        source: ./data
        target: /data
    networks:
      - redis-net
    depends_on:
      - redis
  data-load-billing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=redis_data_load_billing
    image: data-load-billing:latest
    container_name: data-load-billing
    environment:
      - FILENAME=ArchivosBillings
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - REDIS_PASS=TeLcEl
    volumes: 
      - type: bind
        source: ./data
        target: /data
    networks:
      - redis-net
    depends_on:
      - redis
  redis:
    image: registry.redhat.io/rhscl/redis-5-rhel7
    container_name: redis-ephemeral
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=TeLcEl
    networks:
      redis-net:
        aliases:
          - redis-db
networks:
  redis-net: