---
ansible_connection: local

# Create new projects with a given short name and display name
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ namespace }}"
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.12/project-requests/create-project.yml"
    params_from_vars: "{{ project }}"
    action: create
    tags:
      - "{{ namespace }}"

# - object: images
#   content:
#   - name: "redis"
#     file: "{{ redis.build.imagestream.rhel }}"
#     namespace: "{{ namespace }}"
#     tags:
#       - "{{ namespace }}"

- object: carga-series
  content:
  - name: "secrets"
    file: "{{ inventory_dir }}/../templates/secrets.yml"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"
  - name: "redis-series"
    file: "{{ inventory_dir }}/../templates/redis.yml"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"
  - name: "process"
    file: "{{ inventory_dir }}/../templates/carga-series.yml"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"

- object: carga-planes
  content:
  - name: "redis"
    template: "{{ openshift_db_templates_raw }}/{{ openshift_db_templates_raw_version_tag }}/examples/db-templates/redis-ephemeral-template.json"
    params_from_vars: "{{ redis.deploy.planes }}"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"
  - name: "process"
    file: "{{ inventory_dir }}/../templates/carga-planes.yml"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"