---
ansible_connection: local

redis:
  deploy:
    MEMORY_LIMIT: "24G"
    NAMESPACE: "openshift"
    DATABASE_SERVICE_NAME: "redis-perfil-corp"
    REDIS_PASSWORD: "TeLcEl"
    REDIS_VERSION: "5"

data_load:
  series:
    NAME: "carga-redis-series"
    GIT_REPOSITORY_URL: "http://gitlab-community-telcel-ci-cd.apps.paas.telcelcloud.dt/perfilador-corporativo/carga-datos-redis.git"
    GIT_REPOSITORY_REF: "hiredis-omp"
    GIT_SOURCE_SECRET: "gitlab-os"
    APP_RUN: "redis_data_load_series"
    FILENAME: "seriesSiantel081019.txt"
    REDIS_HOST: "{{ redis.deploy.DATABASE_SERVICE_NAME }}"
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "{{ redis.deploy.REDIS_PASSWORD }}"
    REDIS_DATABASE: "0"
    PVC_NAME: "carga-masiva-data"
    CPU_REQ: "3"
    MEMORY_REQ: "3Gi"
    NUM_THREADS: "3"
  planes:
    NAME: "carga-redis-planes"
    GIT_REPOSITORY_URL: "http://gitlab-community-telcel-ci-cd.apps.paas.telcelcloud.dt/perfilador-corporativo/carga-datos-redis.git"
    GIT_REPOSITORY_REF: "master"
    GIT_SOURCE_SECRET: "gitlab-os"
    APP_RUN: "redis_data_load_planes"
    FILENAME: "Planes.txt"
    REDIS_HOST: "{{ redis.deploy.DATABASE_SERVICE_NAME }}"
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "{{ redis.deploy.REDIS_PASSWORD }}"
    REDIS_DATABASE: "1"
    PVC_NAME: "carga-masiva-data"
    CPU_REQ: "100m"
    MEMORY_REQ: "50Mi"
  billing:
    NAME: "carga-redis-billing"
    GIT_REPOSITORY_URL: "http://gitlab-community-telcel-ci-cd.apps.paas.telcelcloud.dt/perfilador-corporativo/carga-datos-redis.git"
    GIT_REPOSITORY_REF: "master"
    GIT_SOURCE_SECRET: "gitlab-os"
    APP_RUN: "redis_data_load_billing"
    FILENAME: "ArchivosBillings"
    REDIS_HOST: "{{ redis.deploy.DATABASE_SERVICE_NAME }}"
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "{{ redis.deploy.REDIS_PASSWORD }}"
    REDIS_DATABASE: "2"
    PVC_NAME: "carga-masiva-data"
    CPU_REQ: "100m"
    MEMORY_REQ: "200Mi"

# Create new projects with a given short name and display name
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ namespace }}"
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/project-requests/create-project.yml"
    params_from_vars: "{{ project }}"
    action: create
    tags:
      - "{{ namespace }}"

- object: secrets
  content:
  - name: "gitlab"
    file: "{{ inventory_dir }}/../templates/secrets/gitlab-private-key.yml"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"

# - object: images
#   content:
#   - name: "redis"
#     file: "{{ redis.build.imagestream.rhel }}"
#     namespace: "{{ namespace }}"
#     tags:
#       - "{{ namespace }}"

- object: redis
  content:
  - name: "redis"
    template: "{{ inventory_dir }}/../templates/redis.yml"
    params_from_vars: "{{ redis.deploy }}"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"

- object: carga-series
  content:
  - name: "app-deploy"
    template: "{{ inventory_dir }}/../templates/data-load-deploy.yml"
    params_from_vars: "{{ data_load.series }}"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"

- object: carga-planes
  content:
  - name: "app-deploy"
    template: "{{ inventory_dir }}/../templates/data-load-deploy.yml"
    params_from_vars: "{{ data_load.planes }}"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"

- object: carga-billing
  content:
  - name: "app-deploy"
    template: "{{ inventory_dir }}/../templates/data-load-deploy.yml"
    params_from_vars: "{{ data_load.billing }}"
    namespace: "{{ namespace }}"
    tags:
      - "{{ namespace }}"
