# Install Ansible Roles
# ---------------------
# When making the Conductor image `ansible-galaxy install -r requirements.yml` is executed
# using this file. Follow the instructions at http://docs.ansible.com/ansible/galaxy.html
# to include any roles you want installed prior to running main.yml.

# From 'openshift-applier'
- src: https://github.com/redhat-cop/openshift-applier
  scm: git
  version: v2.1.1
  name: openshift-applier