apiVersion: v1
kind: Secret
data:
  database-password: VGVMY0Vs
metadata:
  annotations:
    template.openshift.io/expose-password: '{.data[''database-password'']}'
  labels:
    app: redis-ephemeral
    template: redis-ephemeral-template
  name: redis-db-e
type: Opaque
